def print_menu():
    print("===============================")
    print("         AI-SCHOOL OS          ")
    print("===============================")
    print()
    print("1. Add Student")
    print("2. View Students")
    print("3. Search Student")
    print("4. Update Student")
    print("5. Delete Student")
    print("6. Exit")
